CFLAGS_mc_smp.o	+= -march=armv7-a

obj-$(CONFIG_ARCH_SUNXI_MC_SMP) += mc_smp.o headsmp.o
obj-$(CONFIG_ARCH_SUNXI_V7) += sunxi.o
obj-$(CONFIG_ARCH_SUNXI_V5) += sunxi_v5.o
obj-$(CONFIG_SMP) += platsmp.o
